import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const app = $('#app');
const toastEl = $('#toast');
const rand = (a=1,b=0)=>Math.random()*(a-b)+b;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const choice=a=>a[Math.floor(Math.random()*a.length)];
const id=()=>Math.random().toString(36).slice(2,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));

let toastTimer;
function toast(msg){ toastEl.textContent=msg; toastEl.classList.add('show'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toastEl.classList.remove('show'),2200); }

const renderer = new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.1; app.appendChild(renderer.domElement);
const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x06101d,.04);
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,100); camera.position.set(0,.15,7.1);
scene.add(new THREE.HemisphereLight(0xc9f3ff,0x18172a,2.7)); const sun=new THREE.DirectionalLight(0xffe4c7,4.1); sun.position.set(-4,6,5); scene.add(sun); const rim=new THREE.DirectionalLight(0x55dcff,2.1); rim.position.set(5,0,-5); scene.add(rim);
const world=new THREE.Group(); world.rotation.set(-.18,.55,.05); scene.add(world);

const starGeo=new THREE.BufferGeometry(); const starData=[]; for(let i=0;i<700;i++){const r=20+Math.random()*35,u=Math.random()*Math.PI*2,v=Math.acos(2*Math.random()-1);starData.push(r*Math.sin(v)*Math.cos(u),r*Math.cos(v),r*Math.sin(v)*Math.sin(u));} starGeo.setAttribute('position',new THREE.Float32BufferAttribute(starData,3)); scene.add(new THREE.Points(starGeo,new THREE.PointsMaterial({color:0xd8efff,size:.035,transparent:true,opacity:.7})));

const BASE_RADIUS=2.2; let source=new THREE.IcosahedronGeometry(BASE_RADIUS,3); const geometry=source.index?source.toNonIndexed():source; source.dispose?.(); geometry.computeVertexNormals();
const pos=geometry.getAttribute('position'), dirs=[]; for(let i=0;i<pos.count;i++) dirs.push(new THREE.Vector3(pos.getX(i),pos.getY(i),pos.getZ(i)).normalize()); const faceCount=pos.count/3; const colors=new Float32Array(pos.count*3); geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));
const material=new THREE.MeshStandardMaterial({vertexColors:true,roughness:.88,metalness:.02,flatShading:true}); const planet=new THREE.Mesh(geometry,material); world.add(planet);
const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(BASE_RADIUS+.12,48,32),new THREE.MeshBasicMaterial({color:0x6ddfff,transparent:true,opacity:.085,side:THREE.BackSide,depthWrite:false})); world.add(atmosphere);
const palette={water:new THREE.Color('#58cbe3'),deepWater:new THREE.Color('#2f91bd'),land:new THREE.Color('#7faf73'),highLand:new THREE.Color('#a8be80'),forest:new THREE.Color('#315f50'),city:new THREE.Color('#b26b63'),snow:new THREE.Color('#dcecf0')};
let states=Array.from({length:faceCount},()=>({type:'water',altitude:-.28})), decorations=new Map(), seed=Math.random()*1000, activeTool='land';
const faceDirection=f=>dirs[f*3].clone().add(dirs[f*3+1]).add(dirs[f*3+2]).normalize();
function colorFor(s){if(s.type==='water')return s.altitude<-.45?palette.deepWater:palette.water;if(s.type==='forest')return palette.forest;if(s.type==='city')return palette.city;if(s.type==='snow')return palette.snow;return s.altitude>.55?palette.highLand:palette.land;} const radiusFor=s=>BASE_RADIUS+s.altitude*.13;
function disposeObject(o){o.traverse(x=>{x.geometry?.dispose?.(); if(x.material){if(Array.isArray(x.material))x.material.forEach(m=>m.dispose?.());else x.material.dispose?.();}})}
function clearDecoration(face){const old=decorations.get(face);if(!old)return;disposeObject(old);world.remove(old);decorations.delete(face)}
function addDecoration(face){clearDecoration(face);const s=states[face];if(!['forest','city'].includes(s.type))return;const dir=faceDirection(face),group=new THREE.Group();group.position.copy(dir.clone().multiplyScalar(radiusFor(s)+.025));group.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);const seeded=n=>{const x=Math.sin((face+1)*12.9898+n*78.233+seed)*43758.5453;return x-Math.floor(x)};if(s.type==='forest'){for(let i=0;i<3;i++){const tree=new THREE.Group(),trunk=new THREE.Mesh(new THREE.CylinderGeometry(.018,.024,.09,5),new THREE.MeshStandardMaterial({color:0x684b3c,roughness:1}));trunk.position.y=.045;const crown=new THREE.Mesh(new THREE.ConeGeometry(.075+seeded(i)*.025,.19+seeded(i+4)*.06,6),new THREE.MeshStandardMaterial({color:i===1?0x284f43:0x386c52,roughness:1,flatShading:true}));crown.position.y=.16;tree.add(trunk,crown);tree.position.set((seeded(i+8)-.5)*.19,0,(seeded(i+12)-.5)*.19);tree.rotation.y=seeded(i+16)*Math.PI;group.add(tree)}}else{for(let i=0;i<3;i++){const h=new THREE.Group(),w=.07+seeded(i)*.055,ht=.07+seeded(i+4)*.09,body=new THREE.Mesh(new THREE.BoxGeometry(w,ht,w),new THREE.MeshStandardMaterial({color:0xd7a07f,roughness:.95})),roof=new THREE.Mesh(new THREE.ConeGeometry(w*.78,.07,4),new THREE.MeshStandardMaterial({color:0x74455f,roughness:.95}));body.position.y=ht/2;roof.position.y=ht+.035;roof.rotation.y=Math.PI/4;h.add(body,roof);h.position.set((seeded(i+8)-.5)*.2,0,(seeded(i+12)-.5)*.2);h.rotation.y=seeded(i+16)*Math.PI;group.add(h)}} decorations.set(face,group);world.add(group)}
function applyFace(face,rebuild=true){const s=states[face],r=radiusFor(s),c=colorFor(s);for(let k=0;k<3;k++){const i=face*3+k,d=dirs[i];pos.setXYZ(i,d.x*r,d.y*r,d.z*r);colors[i*3]=c.r;colors[i*3+1]=c.g;colors[i*3+2]=c.b}if(rebuild)addDecoration(face)}
function refreshAll(){for(const f of [...decorations.keys()])clearDecoration(f);for(let f=0;f<faceCount;f++)applyFace(f,false);pos.needsUpdate=true;geometry.getAttribute('color').needsUpdate=true;geometry.computeVertexNormals();for(let f=0;f<faceCount;f++)if(['forest','city'].includes(states[f].type))addDecoration(f);refreshNpcMarkers()}
function proceduralValue(dir,face){return Math.sin(dir.x*4.6+seed*.11)+Math.cos(dir.z*5.4-seed*.07)+Math.sin((dir.x+dir.y-dir.z)*7.1+seed*.043)*.75+Math.cos((face%31)*.31+seed)*.22}
function generatePlanet(){seed=Math.random()*10000;for(let f=0;f<faceCount;f++){const d=faceDirection(f),n=proceduralValue(d,f);if(n<-.15)states[f]={type:'water',altitude:clamp(n*.3,-.6,-.12)};else{let type='land';if(n>1.15&&d.y>.1)type='snow';else if(n>.38&&Math.sin(f*2.13+seed)>.1)type='forest';else if(n>.7&&Math.random()<.03)type='city';states[f]={type,altitude:clamp(.12+n*.34,.08,.9)}}}refreshAll()}
const landFaces=()=>states.map((s,i)=>s.type!=='water'?i:-1).filter(i=>i>=0);

const npcLayer=new THREE.Group(); world.add(npcLayer); const npcMeshes=new Map();
function makeNpcTexture(emoji){const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(10,20,32,.88)';x.beginPath();x.arc(64,64,54,0,Math.PI*2);x.fill();x.strokeStyle='rgba(120,235,255,.9)';x.lineWidth=6;x.stroke();x.font='64px serif';x.textAlign='center';x.textBaseline='middle';x.fillText(emoji,64,67);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t}
function createNpcMarker(n){const g=new THREE.Group();const orb=new THREE.Mesh(new THREE.SphereGeometry(.045,10,8),new THREE.MeshBasicMaterial({color:0x8cf3ff}));const spr=new THREE.Sprite(new THREE.SpriteMaterial({map:makeNpcTexture(n.emoji),transparent:true,depthTest:false}));spr.scale.set(.3,.3,.3);spr.position.y=.19;g.add(orb,spr);g.userData.npcId=n.id;npcLayer.add(g);npcMeshes.set(n.id,g);return g}
function refreshNpcMarkers(){for(const n of sim.npcs){let g=npcMeshes.get(n.id)||createNpcMarker(n);const d=new THREE.Vector3(...n.dir).normalize();const face=nearestFace(d);const r=radiusFor(states[face])+.085;g.position.copy(d.multiplyScalar(r));g.visible=n.alive}}
function nearestFace(d){let best=0,dot=-2;for(let f=0;f<faceCount;f++){const x=faceDirection(f).dot(d);if(x>dot){dot=x;best=f}}return best}
function randomLandDir(){const faces=landFaces();return faceDirection(choice(faces.length?faces:[0])).toArray()}

const names=['Mira','Rook','Pip','Sable','Juniper','Kestrel','Nox','Ivy','Tarin','Luma','Bram','Vale','Orin','Faye','Moss','Cinder']; const emojis=['🧑‍🌾','🧙','🧝','🧑‍🔧','🧑‍🍳','🧑‍🎨','🧑‍🚀','🧑‍🔬','🧑‍🏫','🧚']; const traits=['curious','stubborn','kind','ambitious','paranoid','romantic','reckless','patient','greedy','loyal','dramatic','inventive','shy','competitive'];
function makeNpc(custom={}){const n={id:id(),name:custom.name||choice(names),emoji:custom.emoji||choice(emojis),traits:custom.traits||[choice(traits),choice(traits)].filter((x,i,a)=>a.indexOf(x)===i),health:100,hunger:rand(35,5),mood:rand(82,45),goals:custom.goals||['Find a place in the community','Stay fed and safe'],thought:'I should see what this world has for me.',action:'wandering',dir:randomLandDir(),targetDir:null,moveProgress:0,inventory:['berries'],agenda:['Explore nearby land','Find food','Talk to someone'],shortMemories:[],longMemories:['I arrived on this strange little world.'],relationships:{},status:[],alive:true,aiDue:performance.now()+rand(15000,4000),age:Math.floor(rand(58,18)),job:choice(['forager','builder','tinkerer','cook','scout','storyteller']),color:`hsl(${Math.floor(rand(360))} 70% 65%)`};return n}
const sim={day:1,minutes:8*60,paused:false,speed:1,sandbox:true,tech:1,research:0,researchTopic:'Agriculture',worldPrompt:'A tiny hopeful frontier world with room for chaos.',npcs:[],events:[],autoAI:true,llmConnected:false,llmBusy:false,view:'planet',selectedNpcId:null,lastTick:performance.now(),aiRoundRobin:0};
function seedNpcs(count=6){for(const g of npcMeshes.values()){disposeObject(g);npcLayer.remove(g)}npcMeshes.clear();sim.npcs=Array.from({length:count},()=>makeNpc());for(const a of sim.npcs)for(const b of sim.npcs)if(a!==b)a.relationships[b.id]=Math.floor(rand(25,-5));sim.selectedNpcId=sim.npcs[0]?.id||null;refreshNpcMarkers();renderInspector();logEvent('world',`${count} people awaken across the planet.`)}
const selectedNpc=()=>sim.npcs.find(n=>n.id===sim.selectedNpcId)||null;
function simTime(){const h=Math.floor(sim.minutes/60)%24,m=Math.floor(sim.minutes%60);return `Day ${sim.day} · ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`}
function logEvent(type,text,npc=null){sim.events.unshift({id:id(),time:simTime(),type,text,npc:npc?.name||null});sim.events=sim.events.slice(0,180);renderLog()}

function builtInDecision(n){if(!n.alive)return;let action;if(n.hunger>72)action='foraging for food';else if(n.mood<28)action=Math.random()<.5?'seeking company':'brooding alone';else if(Math.random()<.35){const others=sim.npcs.filter(x=>x.alive&&x.id!==n.id).map(x=>x.name);action='talking to '+(others.length?choice(others):'the wind');}else action=choice(['exploring','gathering wood','building a shelter','studying the terrain','resting','crafting a tool','telling a story']);n.action=action;n.thought=choice([`Maybe ${action} will help.`,`I have a feeling something is about to change.`,`I keep thinking about ${choice(n.goals)}.`,`I wonder who I can trust here.`]);n.targetDir=randomLandDir();n.moveProgress=0;if(action.includes('foraging'))n.agenda.unshift('Eat what I find');if(action.includes('building'))sim.research=clamp(sim.research+rand(4,1),0,100)}
function executeNpcAction(n,dt){if(!n.alive)return;n.hunger=clamp(n.hunger+dt*.12*sim.speed,0,100);n.mood=clamp(n.mood+rand(.035,-.03)*dt*sim.speed,0,100);if(n.hunger>90){n.health=clamp(n.health-dt*.18*sim.speed,0,100);if(Math.random()<.003*dt) n.status.push('weak from hunger')}if(n.health<=0){n.alive=false;n.action='dead';logEvent('death',`${n.name} died. The world keeps turning.`,n);return}if(n.targetDir){const cur=new THREE.Vector3(...n.dir).normalize(),tar=new THREE.Vector3(...n.targetDir).normalize();const rate=.09*dt*sim.speed;cur.lerp(tar,clamp(rate,0,1)).normalize();n.dir=cur.toArray();if(cur.dot(tar)>.998){n.targetDir=null;completeAction(n)}}}
function completeAction(n){const a=n.action;if(a.includes('foraging')){const food=Math.floor(rand(4,1));n.inventory.push(...Array(food).fill(choice(['berries','roots','mushrooms'])));n.hunger=clamp(n.hunger-35,0,100);logEvent('npc',`${n.name} found food and ate.`,n)}else if(a.includes('gathering')){n.inventory.push('wood','wood');logEvent('npc',`${n.name} gathered wood.`,n)}else if(a.includes('crafting')){if(n.inventory.includes('wood')){n.inventory.splice(n.inventory.indexOf('wood'),1);n.inventory.push(choice(['wooden tool','cup','carved charm']));logEvent('npc',`${n.name} crafted something new.`,n)}}else if(a.includes('building')){const f=nearestFace(new THREE.Vector3(...n.dir));if(states[f].type!=='water'){states[f].type='city';states[f].altitude=Math.max(states[f].altitude,.2);applyFace(f);pos.needsUpdate=true;geometry.getAttribute('color').needsUpdate=true;n.mood=clamp(n.mood+8,0,100);sim.tech=Math.min(10,sim.tech+(Math.random()<.15?1:0));logEvent('build',`${n.name} expanded a settlement. Tech level is ${sim.tech}.`,n)}}else if(a.includes('talking')){const other=sim.npcs.find(x=>x.alive&&x.id!==n.id&&a.includes(x.name))||choice(sim.npcs.filter(x=>x.alive&&x.id!==n.id));if(other){n.relationships[other.id]=(n.relationships[other.id]||0)+Math.floor(rand(8,-3));other.relationships[n.id]=(other.relationships[n.id]||0)+Math.floor(rand(8,-3));const line=choice([`"Do you ever think the planet is listening?"`,`"I found something odd near the ridge."`,`"We should work together before things get weird."`,`"I don't trust the new rumor going around."`]);n.shortMemories.unshift(`Talked with ${other.name}: ${line}`);other.shortMemories.unshift(`Talked with ${n.name}: ${line}`);logEvent('talk',`${n.name} → ${other.name}: ${line}`,n)}}n.aiDue=performance.now()+rand(17000,7000)/sim.speed}
function tickSim(dt){if(sim.paused)return;sim.minutes+=dt*sim.speed*2.2;if(sim.minutes>=1440){sim.minutes-=1440;sim.day++;logEvent('world',`Day ${sim.day} begins.`)}for(const n of sim.npcs){executeNpcAction(n,dt);if(performance.now()>n.aiDue&&!n.targetDir){if(sim.autoAI&&sim.llmConnected)queueAiDecision(n);else builtInDecision(n)}}if(sim.research>=100){sim.research=0;sim.tech=Math.min(10,sim.tech+1);sim.researchTopic=choice(['Agriculture','Masonry','Medicine','Navigation','Metallurgy','Astronomy']);logEvent('research',`A research breakthrough raises civilization to tech ${sim.tech}. New focus: ${sim.researchTopic}.`)}refreshNpcMarkers();$('#clock').textContent=simTime();$('#npcCount').textContent=`${sim.npcs.filter(n=>n.alive).length} alive`;if(Math.random()<.002*dt*sim.speed)emergentEvent()}
function emergentEvent(){const e=choice(['A flock of luminous birds circles the largest town.','A minor quake rattles the hills.','A patch of giant mushrooms appears overnight.','Someone leaves a mysterious gift at the settlement edge.','The sky glows violet for several minutes.']);logEvent('world',e);for(const n of sim.npcs.filter(x=>x.alive)){n.shortMemories.unshift(e);n.mood=clamp(n.mood+rand(5,-4),0,100)}}

const llm={mode:'proxy',base:'http://127.0.0.1:11434',model:''};
function llmRoot(){return llm.mode==='proxy'?'/ollama':llm.base.replace(/\/$/,'')}
async function connectLlm(){llm.mode=$('#llmMode').value;llm.base=$('#llmUrl').value.trim()||'http://127.0.0.1:11434';setLlmStatus('busy','CONNECTING');try{const r=await fetch(`${llmRoot()}/api/tags`,{signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);const data=await r.json();const models=(data.models||[]).map(x=>x.name);if(!models.length)throw new Error('No Ollama models installed');$('#llmModel').innerHTML=models.map(m=>`<option>${esc(m)}</option>`).join('');llm.model=models[0];sim.llmConnected=true;setLlmStatus('on','CONNECTED');toast(`Ollama connected · ${llm.model}`)}catch(e){sim.llmConnected=false;setLlmStatus('off','OFFLINE');toast(`LLM connection failed: ${e.message}`)}}
function setLlmStatus(cls,text){const el=$('#llmStatus');el.className=`status ${cls}`;el.textContent=text}
async function ollamaJson(messages){if(!sim.llmConnected||sim.llmBusy)return null;sim.llmBusy=true;setLlmStatus('busy','THINKING');try{const r=await fetch(`${llmRoot()}/api/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:llm.model,messages,stream:false,format:'json',options:{temperature:.9,num_predict:450}})});if(!r.ok)throw new Error(await r.text());const data=await r.json();return JSON.parse(data.message?.content||'{}')}catch(e){logEvent('system',`Local AI error: ${e.message}`);return null}finally{sim.llmBusy=false;setLlmStatus(sim.llmConnected?'on':'off',sim.llmConnected?'CONNECTED':'OFFLINE')}}
function worldSnapshot(focus){const alive=sim.npcs.filter(n=>n.alive);return {time:simTime(),tech:sim.tech,research:{topic:sim.researchTopic,progress:Math.round(sim.research)},population:alive.map(n=>({name:n.name,traits:n.traits,health:Math.round(n.health),hunger:Math.round(n.hunger),mood:Math.round(n.mood),action:n.action,goals:n.goals,inventory:n.inventory.slice(-8),relationships:Object.fromEntries(Object.entries(n.relationships).map(([k,v])=>[sim.npcs.find(x=>x.id===k)?.name||k,v]))})),recentEvents:sim.events.slice(0,8).map(e=>e.text),focus:focus?{name:focus.name,thought:focus.thought,memories:[...focus.shortMemories.slice(0,5),...focus.longMemories.slice(0,3)]}:null}}
async function queueAiDecision(n,extra=''){if(sim.llmBusy||!n.alive)return;n.aiDue=performance.now()+7000;const snap=worldSnapshot(n);const sys=`You are the decision engine for a living NPC in a tiny emergent planet simulation. Stay in character. Make one plausible next action based on needs, goals, memories, relationships and world events. Actions can include moving, talking, gathering, eating, crafting, building, researching, helping, arguing, resting, investigating, using an item. Return ONLY JSON with keys: thought (string), action (short string), speech (string or empty), targetNpc (name or empty), memory (string), moodDelta (number -15..15), hungerDelta (number -10..10), goalDelta (optional short new goal or empty). Do not narrate outside JSON.`;const user=`WORLD STATE:\n${JSON.stringify(snap)}\n${extra?`PLAYER INFLUENCE: ${extra}\n`:''}Decide what ${n.name} does next.`;const out=await ollamaJson([{role:'system',content:sys},{role:'user',content:user}]);if(!out)return builtInDecision(n);n.thought=String(out.thought||n.thought).slice(0,240);n.action=String(out.action||'wandering').slice(0,120);n.mood=clamp(n.mood+Number(out.moodDelta||0),0,100);n.hunger=clamp(n.hunger+Number(out.hungerDelta||0),0,100);if(out.goalDelta)n.goals.unshift(String(out.goalDelta).slice(0,120));if(out.memory)n.shortMemories.unshift(String(out.memory).slice(0,300));if(out.speech){const t=sim.npcs.find(x=>x.alive&&x.name.toLowerCase()===String(out.targetNpc||'').toLowerCase());logEvent('talk',`${n.name}${t?` → ${t.name}`:''}: “${String(out.speech).slice(0,220)}”`,n);if(t){n.relationships[t.id]=(n.relationships[t.id]||0)+Math.floor(rand(5,-2));t.shortMemories.unshift(`${n.name} said: ${String(out.speech).slice(0,220)}`)}}else logEvent('ai',`${n.name} decides to ${n.action}.`,n);n.targetDir=randomLandDir();n.aiDue=performance.now()+rand(22000,9000)/sim.speed;renderInspector()}
async function influenceWorld(text){text=text.trim();if(!text)return;logEvent('player',`⚡ You influence the world: ${text}`);for(const n of sim.npcs.filter(x=>x.alive)){n.shortMemories.unshift(`A strange outside influence: ${text}`);n.mood=clamp(n.mood+rand(6,-6),0,100)}if(sim.llmConnected){const focus=selectedNpc()||choice(sim.npcs.filter(x=>x.alive));const sys=`You are a world event director for a tiny AI society simulation. Interpret the player's influence as an event, rumor, temptation, disaster, blessing, social disruption, or environmental change. Return ONLY JSON: {"event":"one vivid sentence","affected":["NPC names"],"moodDelta":number -15..15,"hungerDelta":number -15..15,"status":"optional status effect or empty","researchDelta":number 0..20}. Do not invent NPC names not in the state.`;const out=await ollamaJson([{role:'system',content:sys},{role:'user',content:`STATE ${JSON.stringify(worldSnapshot(focus))}\nPLAYER INFLUENCE: ${text}`}]);if(out?.event){logEvent('world',String(out.event));const affected=(out.affected||[]).map(String);for(const n of sim.npcs.filter(x=>!affected.length||affected.includes(x.name))){n.mood=clamp(n.mood+Number(out.moodDelta||0),0,100);n.hunger=clamp(n.hunger+Number(out.hungerDelta||0),0,100);if(out.status&&!n.status.includes(out.status))n.status.push(String(out.status));n.shortMemories.unshift(String(out.event))}sim.research=clamp(sim.research+Number(out.researchDelta||0),0,100)}}else applyKeywordInfluence(text);renderInspector();$('#influenceInput').value=''}
function applyKeywordInfluence(text){const t=text.toLowerCase();if(/scarce|famine|hunger/.test(t))sim.npcs.forEach(n=>n.hunger=clamp(n.hunger+25,0,100));if(/festival|party|celebrat/.test(t))sim.npcs.forEach(n=>n.mood=clamp(n.mood+18,0,100));if(/storm|quake|disaster/.test(t))sim.npcs.forEach(n=>n.mood=clamp(n.mood-10,0,100));if(/food|berries|feast/.test(t))sim.npcs.forEach(n=>n.inventory.push('berries'));}

function renderInspector(){const n=selectedNpc(),empty=$('#npcEmpty'),card=$('#npcCard');$('#npcPicker').innerHTML=sim.npcs.map(x=>`<option value="${x.id}" ${x.id===sim.selectedNpcId?'selected':''}>${esc(x.emoji+' '+x.name)}${x.alive?'':' (dead)'}</option>`).join('');if(!n){empty.hidden=false;card.hidden=true;return}empty.hidden=true;card.hidden=false;$('#npcAvatar').textContent=n.emoji;$('#npcName').value=n.name;$('#npcTraits').innerHTML=n.traits.map(t=>`<span>${esc(t)}</span>`).join('');for(const k of ['health','hunger','mood']){$(`#${k}Bar`).value=n[k];$(`#${k}Text`).textContent=Math.round(n[k])}$('#npcAction').textContent=n.action;$('#npcThought').textContent=n.thought;$('#npcGoals').value=n.goals.join('\n');const rel=Object.entries(n.relationships).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([k,v])=>`${sim.npcs.find(x=>x.id===k)?.name||'?'}: ${v>=0?'+':''}${v}`).join(', ');$('#npcDetails').textContent=`Age: ${n.age} · Job: ${n.job}\nStatus: ${n.status.join(', ')||'none'}\nInventory: ${n.inventory.join(', ')||'empty'}\nAgenda:\n• ${n.agenda.join('\n• ')}\nRelationships: ${rel||'none yet'}`}
function renderLog(){const list=$('#logList');if(!list)return;list.innerHTML=sim.events.map(e=>`<div class="log-entry"><div class="log-time">${esc(e.time)}${e.npc?` · ${esc(e.npc)}`:''}</div>${esc(e.text)}</div>`).join('')}
function showMemories(){const n=selectedNpc();if(!n)return;$('#modalTitle').textContent=`${n.name}'s memories`;$('#modalBody').innerHTML=`<h3>Short-term</h3><div class="modal-list">${(n.shortMemories.length?n.shortMemories:['Nothing yet.']).map(m=>`<div class="memory">${esc(m)}</div>`).join('')}</div><h3>Long-term</h3><div class="modal-list">${n.longMemories.map(m=>`<div class="memory">${esc(m)}</div>`).join('')}</div><p><button id="promoteMemory">Promote newest short memory</button> <button id="clearShort">Clear short memories</button></p>`;$('#modal').showModal();$('#promoteMemory')?.addEventListener('click',e=>{e.preventDefault();if(n.shortMemories[0])n.longMemories.unshift(n.shortMemories[0]);showMemories()});$('#clearShort')?.addEventListener('click',e=>{e.preventDefault();n.shortMemories=[];showMemories()})}
function createNpcDialog(){if(!sim.sandbox&&sim.npcs.filter(n=>n.alive).length>=7)return toast('Non-sandbox population limit reached.');$('#modalTitle').textContent='Create NPC';$('#modalBody').innerHTML=`<label>Name <input id="newNpcName" value="${choice(names)}"></label><label>Emoji <input id="newNpcEmoji" value="${choice(emojis)}"></label><label>Traits <input id="newNpcTraits" value="${choice(traits)}, ${choice(traits)}"></label><label>Goals <textarea id="newNpcGoals">Find a purpose\nMeet the locals</textarea></label><p><button id="createNpcConfirm">Create on planet</button></p>`;$('#modal').showModal();$('#createNpcConfirm').addEventListener('click',e=>{e.preventDefault();const n=makeNpc({name:$('#newNpcName').value||choice(names),emoji:$('#newNpcEmoji').value||'🧑',traits:$('#newNpcTraits').value.split(',').map(x=>x.trim()).filter(Boolean),goals:$('#newNpcGoals').value.split('\n').filter(Boolean)});for(const o of sim.npcs){n.relationships[o.id]=0;o.relationships[n.id]=0}sim.npcs.push(n);sim.selectedNpcId=n.id;refreshNpcMarkers();renderInspector();logEvent('world',`${n.name} enters the world.`);$('#modal').close()})}
function overrideAction(){const n=selectedNpc();if(!n)return;$('#modalTitle').textContent=`Override ${n.name}`;$('#modalBody').innerHTML=`<label>Force current action <input id="overrideText" placeholder="e.g. confront Mira about the relic"></label><p><button id="overrideConfirm">Do it</button></p>`;$('#modal').showModal();$('#overrideConfirm').addEventListener('click',e=>{e.preventDefault();const x=$('#overrideText').value.trim();if(x){n.action=x;n.thought=`I feel compelled to ${x}.`;n.targetDir=randomLandDir();n.shortMemories.unshift(`An outside force compelled me to ${x}.`);logEvent('player',`You override ${n.name}: ${x}`,n)}$('#modal').close();renderInspector()})}

function setView(v){sim.view=v;$$('.view').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('#chronicle').hidden=v!=='log';if(v==='planet')targetCam=7.1;if(v==='settlement')targetCam=5.3;if(v==='follow')targetCam=4.5;if(v==='log')targetCam=7.1;toast(v==='follow'&&!selectedNpc()?'Select an NPC first':`${v[0].toUpperCase()+v.slice(1)} view`)}
let targetCam=7.1;
function focusSelected(dt){if(sim.view!=='follow')return;const n=selectedNpc();if(!n)return;const local=new THREE.Vector3(...n.dir).normalize();const worldDir=local.clone().applyQuaternion(world.quaternion);const desired=new THREE.Quaternion().setFromUnitVectors(worldDir,new THREE.Vector3(0,0,1));world.quaternion.slerp(desired.multiply(world.quaternion),clamp(dt*.7,0,1))}

const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let dragging=false,moved=false,last={x:0,y:0};
renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;moved=false;last={x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-last.x,dy=e.clientY-last.y;if(Math.abs(dx)+Math.abs(dy)>3)moved=true;if(sim.view!=='follow'){world.rotation.y+=dx*.005;world.rotation.x=clamp(world.rotation.x+dy*.005,-1.3,1.3)}last={x:e.clientX,y:e.clientY}});renderer.domElement.addEventListener('pointerup',e=>{dragging=false;if(!moved)handleCanvasClick(e)});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();targetCam=clamp(targetCam+e.deltaY*.003,3.8,9)},{passive:false});
function handleCanvasClick(e){const rect=renderer.domElement.getBoundingClientRect();pointer.x=(e.clientX-rect.left)/rect.width*2-1;pointer.y=-(e.clientY-rect.top)/rect.height*2+1;raycaster.setFromCamera(pointer,camera);const npcHits=raycaster.intersectObjects([...npcMeshes.values()],true);if(npcHits.length){let o=npcHits[0].object;while(o&&!o.userData.npcId)o=o.parent;if(o?.userData.npcId){sim.selectedNpcId=o.userData.npcId;renderInspector();return}}const hit=raycaster.intersectObject(planet,false)[0];if(!hit)return;const face=hit.faceIndex;paintFace(face)}
function paintFace(face){const s=states[face];if(activeTool==='lower'){s.altitude=clamp(s.altitude-.18,-.65,.9);if(s.altitude<-.12)s.type='water'}else if(activeTool==='water'){s.type='water';s.altitude=Math.min(s.altitude,-.18)}else{s.type=activeTool;s.altitude=Math.max(s.altitude,.12);if(activeTool==='land')s.altitude=clamp(s.altitude+.12,.12,.9)}applyFace(face);pos.needsUpdate=true;geometry.getAttribute('color').needsUpdate=true;geometry.computeVertexNormals()}

function saveWorld(){const data={version:2,seed,states,sim:{...sim,npcs:sim.npcs,events:sim.events,llmConnected:false,llmBusy:false,lastTick:0},llm:{...llm,model:$('#llmModel').value}};localStorage.setItem('tinyPlanetNpcChaos',JSON.stringify(data));toast('World saved locally')}
function loadWorld(){try{const d=JSON.parse(localStorage.getItem('tinyPlanetNpcChaos'));if(!d)throw new Error('No save found');seed=d.seed;states=d.states;Object.assign(sim,d.sim,{llmConnected:false,llmBusy:false,lastTick:performance.now()});Object.assign(llm,d.llm||{});$('#llmUrl').value=llm.base||'http://127.0.0.1:11434';$('#llmMode').value=llm.mode||'proxy';for(const g of npcMeshes.values()){disposeObject(g);npcLayer.remove(g)}npcMeshes.clear();refreshAll();renderInspector();renderLog();toast('World loaded')}catch(e){toast(e.message)}}
function resetWorld(){generatePlanet();sim.day=1;sim.minutes=480;sim.tech=1;sim.research=0;sim.events=[];seedNpcs(6);renderLog();toast('New world generated')}

$$('.tool').forEach(b=>b.addEventListener('click',()=>{activeTool=b.dataset.tool;$$('.tool').forEach(x=>x.classList.toggle('active',x===b))}));$$('.view').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$$('[data-event]').forEach(b=>b.addEventListener('click',()=>influenceWorld(b.dataset.event)));
$('#pauseBtn').addEventListener('click',()=>{sim.paused=!sim.paused;$('#pauseBtn').textContent=sim.paused?'▶ Resume':'⏸ Pause'});$('#speedSelect').addEventListener('change',e=>sim.speed=Number(e.target.value));$('#sandboxToggle').addEventListener('change',e=>{sim.sandbox=e.target.checked;toast(`Sandbox ${sim.sandbox?'on':'off'}`)});$('#addNpcBtn').addEventListener('click',createNpcDialog);$('#saveBtn').addEventListener('click',saveWorld);$('#loadBtn').addEventListener('click',loadWorld);$('#newBtn').addEventListener('click',resetWorld);$('#connectLlmBtn').addEventListener('click',connectLlm);$('#llmModel').addEventListener('change',e=>llm.model=e.target.value);$('#llmMode').addEventListener('change',e=>llm.mode=e.target.value);$('#autoAiBtn').addEventListener('click',e=>{sim.autoAI=!sim.autoAI;e.currentTarget.classList.toggle('active',sim.autoAI);e.currentTarget.textContent=`🤖 Auto AI: ${sim.autoAI?'ON':'OFF'}`});$('#influenceBtn').addEventListener('click',()=>influenceWorld($('#influenceInput').value));$('#influenceInput').addEventListener('keydown',e=>{if(e.key==='Enter')influenceWorld(e.currentTarget.value)});$('#npcPicker').addEventListener('change',e=>{sim.selectedNpcId=e.target.value;renderInspector()});$('#applyNpcBtn').addEventListener('click',()=>{const n=selectedNpc();if(!n)return;n.name=$('#npcName').value.trim()||n.name;n.goals=$('#npcGoals').value.split('\n').map(x=>x.trim()).filter(Boolean);toast('NPC edits applied');renderInspector()});$('#thinkNowBtn').addEventListener('click',()=>{const n=selectedNpc();if(!n)return;if(sim.llmConnected)queueAiDecision(n,'The player is watching closely and asks you to decide now.');else{builtInDecision(n);renderInspector();toast('Built-in AI made a decision')}});$('#overrideBtn').addEventListener('click',overrideAction);$('#memoryBtn').addEventListener('click',showMemories);$('#clearLogBtn').addEventListener('click',()=>{sim.events=[];renderLog()});

function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)} addEventListener('resize',resize);
let prev=performance.now(), inspectorTimer=0;function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-prev)/1000,.1);prev=now;tickSim(dt);focusSelected(dt);camera.position.z+=(targetCam-camera.position.z)*clamp(dt*4,0,1);world.rotation.y+=sim.paused?0:.025*dt;inspectorTimer+=dt;if(inspectorTimer>.5){inspectorTimer=0;renderInspector()}renderer.render(scene,camera)}

generatePlanet();seedNpcs(6);renderLog();renderInspector();requestAnimationFrame(animate);
